#!/bin/bash
# Name: Philip Scheirich
# Course ID: COMP2137 - Linux Automation
# Professor: D. Simpson
# Date: October 19th, 2023

#Source to get OS information
source /etc/os-release
#Set the variable for the user
myname=`whoami`
#Get the current time and date
TIME=$(date +"%T")
#Get the hostname
HOSTNAME=$(hostname)
#Extract OS info from variables in /etc/os-releases
DISTRO="$NAME $VERSION"
#Show system uptime
UPTIME=$(uptime -p)
#Find specific CPU information
CPU_Details=$(cat /proc/cpuinfo)
#Find current CPU speed
CPU_Speed=$(lscpu -e=+MHZ)
#Find current amount of free RAM
RAM_Size=$(free -h | awk '/^Mem:/ {print $2}')
#Display Disk information
DISK_info=$(lsblk -d -o NAME,MODEL,SIZE | grep -v "NAME")
#Video card information
VIDEO_card=$(lspci | grep -i "VGA")
#Display FQDN information
FQDN_info=$(hostname --fqdn)
#Show Host IP address
IP_address=$(hostname --ip-address)
#Show Default Gateway Information
GATEWAY_ip=$(ip route | awk '/default/ {print $3}')
#DNS Server details
DNS_servers=$(cat /etc/resolv.conf | grep 'nameserver' | awk '{print $2}')
#Display Interface information
INTERFACE_names=$(ip link | awk -F ": " '{print $2}' | awk '{print $1}')
INTERFACE="ens33"
#Display IP address in CIDR format
IP_cidr1=$(ip -o -4 addr show dev ens33 | awk '{print $4}')
IP_cidr2=$(ip -o -4 addr show dev ens34 | awk '{print $4}')
#Show who is currently logged into the system
LOGGED_in=$(who)
#Amount of disk space currently available
DISK_space=$(df -h)
#Display the Process Count and remove header line
PROCESS_count=$(ps aux | wc -l)
PROCESS_count=$((PROCESS_count - 1))
#Display the load averages
LOAD_averages=$(uptime | awk -F 'load average: ' '{print $2}')
#Display memory allocation in MB
MEMORY_info=$(free -m)
#Display the listening network ports
LISTEN_ports=$(ss -tuln)
#Display UFW rules
UFW_rules=$(sudo ufw status)


echo "
System Report generated by $myname on $TIME

SYSTEM INFORMATION
==================
Hostname: $HOSTNAME
OS: $DISTRO
Uptime: $UPTIME

HARDWARE INFORMATION
====================
All CPU INFORMATION: 
$CPU_Details

CPU SPEED: 
$CPU_Speed

RAM: 
$RAM_Size

DISKS:
$DISK_info

VIDEO CARD:
$VIDEO_card

NETWORK INFORMATION
===================

FQDN:
$FQDN_info

HOST ADDRESS:
$IP_address

GATEWAY IP:
$GATEWAY_ip

DNS SERVER:
$DNS_servers

INTERFACE NAMES:
$INTERFACE_names

IP Address: IP Address in CIDR FORMAT
ens33:
$IP_cidr1
ens34:
$IP_cidr2


SYSTEM STATUS
=============

USERS LOGGED IN:
$LOGGED_in

DISK SPACE:
$DISK_space

PROCESS COUNT:
$PROCESS_count

LOAD AVERAGES:
$LOAD_averages

MEMORY ALLOCATION:
$MEMORY_info

LISTENING NETWORK PORTS:
$LISTEN_ports

UFW RULES:
$UFW_rules

That is all of the information. 
Thank you for viewing my script results.
"
